# Ejercicio: Extracción de noticias con Mediastack API

**Objetivo**:  
Escribir un script en Python que recupere noticias de **antena3** y **lasextanoticias** del día de cumpleaños del alumno en 2024 usando Mediastack API, y las almacene en un archivo CSV con los campos requeridos.

---

## Enunciado

1. **Registro en Mediastack**:
   - Obtén una clave de API gratuita registrándote en [mediastack.com](https://mediastack.com/).

2. **Requisitos del Script**:
   - Utiliza la API de Mediastack para recuperar noticias de las fuentes `antena3` y `lasextanoticias`.
   - Filtra las noticias por el **día de tu cumpleaños en 2024** (formato de fecha: `YYYY-MM-DD`).
   - Combina los resultados de ambas fuentes en una única tabla.
   - Guarda la tabla en un archivo CSV con las columnas:  
     `autor`, `titulo`, `descripcion`, `url`, `fuente`, `fechapublicacion`.

3. **Especificaciones Técnicas**:
   - Usa la librería `requests` para llamar a la API.
   - Usa `pandas` para estructurar los datos y guardar el CSV.
   - Encapsúlalo en un script

Cuidado tienes solo 100 llamadas!

In [28]:
import requests
import pandas as pd
import json

pd.set_option('max_colwidth', None)

In [18]:
url = "http://api.mediastack.com/v1/news?access_key=67f7b286232bf5d45c0e7aeb1848c0fb"

params = {'sources': 'antena3, lasextanoticias',
          'countries': 'es',
          'languages': 'es',
          'date': '2024-12-12',
          'limit': 100,
          'offset': 100}

response = requests.get(url, params=params)
print(response)

<Response [200]>

In [21]:
json.loads(response.content)

{'pagination': {'limit': 100, 'offset': 100, 'count': 100, 'total': 996},
 'data': [{'author': 'efe',
   'title': 'Robert Kennedy Jr. propone a su nuera como subdirectora de la CIA para esclarecer el asesinato de JFK',
   'description': '¿Por qué es importante? Robert Kennedy Jr. sospecha que la CIA estuvo involucrada en lo ocurrido. Donald Trump ha prometido hacer públicos los últimos archivos del asesinato de John F. Kennedy.',
   'url': 'https://www.lasexta.com/noticias/internacional/robert-kennedy-propone-nuera-como-subdirectora-cia-esclarecer-asesinato-jfk_20241212675aa851a425820001380ee4.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages01/2024/12/12/31C6C34A-4F03-4715-A489-8CBB72CF2ECF/imagen-archivo-john-kennedy-jackie-onassis_96.jpg?crop=1920,1080,x0,y13&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T09:12:47+00:00'},
  {'author': 'europa-press',
   'title': 'El Ejército israelí inicia su retirada del sur de Líbano',
   'description': '¿Por qué es importante?: Se trata del primer paso importante en la implementación de un cese duradero de las hostilidades y que ha tenido lugar dos semanas después de firmar un alto el fuego temporal entre Israel e Hizbulá.\xa0',
   'url': 'https://www.lasexta.com/noticias/internacional/ejercito-israeli-inicia-retirada-sur-libano_20241212675aa5679439f90001e0f2ea.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages01/2024/12/12/DFE7FF62-806D-4398-9E16-AB0EB9A411BB/efectivos-fuerza-interina-naciones-unidas-libano-finul-jiam-sur-libano_96.jpg?crop=1347,758,x0,y13&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T08:57:11+00:00'},
  {'author': 'lasextacom | agencias',
   'title': 'Cataluña activa la prealerta por posibles riadas en cuatro comarcas de Tarragona debido a lluvias intensas',
   'description': "Posibles crecidas de barrancos: La Confederación Hidrográfica del Ebro (CHE) ha activado la prealerta en las comarcas del Montsià, el Baix Ebre, la Ribera d'Ebre y la Terra Alta (Tarragona).",
   'url': 'https://www.lasexta.com/noticias/sociedad/cataluna-activa-prealerta-posibles-riadas-cuatro-comarcas-tarragona-debido-lluvias-intensas_20241212675aa14dc98fe80001844ffa.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages01/2023/09/14/57D84828-FF51-4079-A479-D0CFCCE9071B/mujer-pasea-lluvia-protegida-paraguas_96.jpg?crop=3133,1762,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T08:42:24+00:00'},
  {'author': 'efe',
   'title': 'Trump planea permitir arrestos de inmigrantes en escuelas, iglesias y juzgados',
   'description': 'Entre líneas:\xa0La política de limitar las acciones de los agentes de inmigración en lugares sensibles fue establecida en el Gobierno de Obama, conocido como el jefe de deportaciones por el alto número de expulsiones realizadas en sus dos mandatos.',
   'url': 'https://www.lasexta.com/noticias/internacional/trump-planea-permitir-arrestos-inmigrantes-escuelas-iglesias-juzgados_20241212675aa0fea4258200013806d8.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages01/2024/11/26/D7E55ED8-ACB2-4E0B-83FE-61660E86049C/donald-trump-presidente-electo-estados-unidos_96.jpg?crop=4262,2397,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T08:38:22+00:00'},
  {'author': 'lasexta-deportes',
   'title': 'Jorge Martín carga contra Ducati: "El trato que tuvieron no me gustó"',
   'description': 'El campeón del mundo de MotoGP ha analizado la decisión del equipo italiano de fichar a Marc Márquez y no a él.\xa0',
   'url': 'https://www.lasexta.com/noticias/deportes/motor/jorge-martin-carga-ducati-trato-que-tuvieron-gusto_20241212675a9f0bc98fe80001844dd2.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages02/2024/11/05/607F4A98-B281-4D1D-B07A-04553F27B443/jorge-martin_96.jpg?crop=3500,1969,x0,y200&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T08:30:03+00:00'},
  {'author': 'Gema, Soubrier',
   'title': 'Basi y su familia, arruinados por su \'inquiokupa\', un refugiado sirio: "Yo también soy vulnerable"',
   'description': 'El inquiokupa de Basi le esta haciendo la vida imposible. Lleva cuatro años sin pagarle el alquiler, le debe más de 37.000 euros. Basí vive una pesadilla, tiene 70.000 euros de deuda, está en el listado de morosos y además tiene que pagar una hipoteca de casi mil euros.',
   'url': 'https://www.antena3.com/programas/espejo-publico/basi-familia-arruinados-inquiokupa-refugiado-sirio-tambien-soy-vulnerable_20241212675a9bb39439f90001e0e913.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/11/B10EED65-78B6-483C-88D3-0BEF8FE4428F/arruinada-inquiokupa_96.jpg?crop=1920,1080,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T08:15:47+00:00'},
  {'author': 'Alberto Mendo',
   'title': 'Así engañó Abraham Mateo a su ídolo, David Bustamante, para que no le reconociera en Mask Singer',
   'description': "Entre sus actuaciones como Mosca, su mayor reto fue el dueto con David Bustamante cantando 'Dos hombres y un destino' sin levantar sospechas precisamente en el invitado.",
   'url': 'https://www.antena3.com/programas/mask-singer/asi-engano-abraham-mateo-idolo-david-bustamante_20241212675a9ac1a42582000138009d.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/12/0D4C9BCB-9DDD-43FB-AAF7-2800C9F1EDA2/96.jpg?crop=1372,772,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T08:11:45+00:00'},
  {'author': 'lasextacom',
   'title': 'Última hora política, en directo | Ábalos declara en el Supremo para intentar "desmontar" las acusaciones de Aldama y la UCO',
   'description': 'El exministro de Transportes José Luis Ábalos declarará este jueves, a las 10.00 horas, en el Tribunal Supremo para intentar ir "desmontando las mentiras" que achaca al presunto comisionista del caso Koldo y al informe de la UCO, que le atribuye un papel relevante en la supuesta trama de adjudicaciones irregulares.',
   'url': 'https://www.lasexta.com/noticias/nacional/ultima-hora-politica-directo-abalos-declara-supremo-intentar-desmontar-acusaciones-aldama-uco_20241212675a9919a42582000137feba.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages01/2024/12/12/54531601-1616-416D-991E-C61C97BFED9C/abalos-declara-supremo-intentar-desmontar-acusaciones-aldama-uco_96.jpg?crop=1920,1080,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T08:04:57+00:00'},
  {'author': 'lasexta-deportes',
   'title': 'Ducati señala qué es lo que más les ha impresionado de Marc Márquez',
   'description': 'Michelle Pirro, piloto de pruebas de Ducati, ha destacado la frenada del octocampeón en las curvas de izquierdas, donde es "especialmente rápido".',
   'url': 'https://www.lasexta.com/noticias/deportes/motor/ducati-senala-que-que-mas-les-impresionado-marc-marquez_20241212675a972fa42582000137fca2.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages02/2024/11/20/DA86DF91-1F74-4116-9ED1-EAD0B89961DF/marc-marquez-ducati_96.jpg?crop=3500,1969,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T07:56:31+00:00'},
  {'author': 'efe',
   'title': 'Consumo investiga a empresas que gestionan cientos de pisos turísticos por posibles "prácticas engañosas"',
   'description': '¿Qué buscan?: La investigación se centra en operaciones de pisos turísticos que, aún teniendo licencia, podrían estar siendo gestionados de forma irregular por empresas intermedias,',
   'url': 'https://www.lasexta.com/noticias/economia/consumo-investiga-empresas-que-gestionan-cientos-pisos-turisticos-posibles-practicas-enganosas_20241212675a92d5c98fe80001844260.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages01/2024/12/12/D2483540-47F4-4A49-8CAE-58FC12546262/caja-seguridad-llaves-piso-alquiler-turistico-17-junio-2024-madrid-espana_96.jpg?crop=1920,1080,x0,y307&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T07:37:57+00:00'},
  {'author': 'alfonso-perez-medina',
   'title': 'La Fiscalía intentará demostrar durante el interrogatorio que Ábalos era el "superjefe" de una organización criminal',
   'description': 'Las pruebas: Fuentes fiscales señalan a laSexta que usarán el "resto de evidencias" que aparecen en el sumario del caso Koldo para intentar demostrar que el exministro dirigía una organización criminal.\xa0',
   'url': 'https://www.lasexta.com/noticias/nacional/fiscalia-intentara-demostrar-interrogatorio-que-abalos-era-superjefe-organizacion-criminal_20241212675a910cc98fe80001843fdf.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages01/2024/12/12/269BDAE9-1B0D-41C6-847F-2C73434A9B1A/imagen-archivo-exministro-exdirigente-socialista-jose-luis-abalos_96.jpg?crop=1920,1080,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T07:30:20+00:00'},
  {'author': 'Roberto Fernández Ferreira',
   'title': 'Abraham Mateo se destapa como Mosca y gana la cuarta temporada de Mask Singer',
   'description': 'El artista ha conseguido mantener a salvo su identidad hasta el final haciéndose así con la máscara dorada.',
   'url': 'https://www.antena3.com/programas/mask-singer/abraham-mateo-mosca-gana_20241212675a2a859439f90001e09f71.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/12/18F4CBA8-A53F-434E-A03D-A56001B9946D/abraham-mateo-destapa-como-mosca-gana-cuarta-temporada-mask-singer_96.jpg?crop=1920,1080,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T00:12:53+00:00'},
  {'author': 'Roberto Fernández Ferreira',
   'title': '¡Adriana Ugarte era Cobra!: la actriz ha sido desenmascarada en la Gran Final de Mask Singer',
   'description': 'La actriz ha acariciado la máscara dorada y pese a no haber ganado, se ha consagrado como una de las revelaciones de la temporada.',
   'url': 'https://www.antena3.com/programas/mask-singer/adriana-ugarte-cobra_20241212675a2897c98fe80001840235.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/12/85569C00-6894-4B06-8C69-EA27CF1AC3E1/adriana-ugarte-era-cobra-actriz-sido-desenmascarada-gran-final-mask-singer_96.jpg?crop=1920,1080,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-12T00:04:39+00:00'},
  {'author': 'Eire García Arbaizar',
   'title': '¡Cobra VS Mosca! Así ha sido el asalto final en Mask Singer',
   'description': 'Los dos animales se han dejado la piel en el escenario defendiendo sus canciones.\xa0\xa0',
   'url': 'https://www.antena3.com/programas/mask-singer/cobra-mosca-asi-sido-asalto-final_20241212675a26f8a42582000137b585.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/11/64AF225E-BE1F-4BD0-975F-9F7E085BF8A5/cobra-mosca-asi-sido-asalto-final-mask-singer_96.jpg?crop=870,489,x0,y12&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T23:57:44+00:00'},
  {'author': 'Roberto Fernández Ferreira',
   'title': "Manuel Díaz, 'El Cordobés', cambia el toro por el Tiburón en Mask Singer: ¡Así ha sido su desenmascaramiento!",
   'description': 'El primer desenmascaramiento de la Gran Final ha dejado a todos boquiabiertos y no ha otorgado ningún punto a los investigadores.',
   'url': 'https://www.antena3.com/programas/mask-singer/manuel-diaz-cordobes-tiburon_20241212675a251fa42582000137b482.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/12/5B838AE7-7D0C-4403-A4B7-7DC8B5E9EF56/manuel-diaz-cordobes-cambia-toro-tiburon-mask-singer-asi-sido-desenmascaramiento_96.jpg?crop=1920,1080,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T23:49:51+00:00'},
  {'author': 'Eire García Arbaizar',
   'title': '¡Tiburón VS Cobra! Así ha sido el primer asalto de la Gran Final',
   'description': 'Las dos máscaras se han enfrentado en un difícil reto que no ha dejado indiferente a nadie.\xa0\xa0',
   'url': 'https://www.antena3.com/programas/mask-singer/tiburon-cobra-asi-sido-primer-asalto-gran-final_20241212675a23979439f90001e09b95.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/11/93D3AEF1-1BB9-4160-B169-8816024BEE9B/tiburon-cobra-asi-sido-primer-asalto-gran-final_96.jpg?crop=1162,654,x0,y40&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T23:43:19+00:00'},
  {'author': 'Patri Bea',
   'title': '¡Hipnótica! Cobra brilla con Las 12 en la gran final de Mask Singer',
   'description': 'La finalista ha escogido uno de los temas más conocidos de Ana Mena para luchar por la victoria y la máscara dorada.\xa0',
   'url': 'https://www.antena3.com/programas/mask-singer/hipnotica-cobra-brilla-12-gran-final_20241212675a1d49a42582000137b02c.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/11/6E23C5CD-296E-45C1-8746-6C16710A580D/hipnotica-cobra-brilla-12-gran-final-mask-singer_96.jpg?crop=8256,4644,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T23:16:25+00:00'},
  {'author': 'Patri Bea',
   'title': '“Mi buen reptar me ha dado más de una alegría”: Cobra podría estar vinculada con el baile según sus últimas pistas',
   'description': 'La finalista ha dejado caer que su forma de moverse le ha dado muy buenos resultados en su vida. ¿Será bailarina?\xa0',
   'url': 'https://www.antena3.com/programas/mask-singer/buen-reptar-dado-mas-alegria-cobra-podria-estar-vinculada-baile-segun-sus-ultimas-pistas_20241212675a1cc4a42582000137afe1.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/11/C4D957D0-72E7-425B-A0D8-E4F9B8FB5207/buen-reptar-dado-mas-alegria-cobra-podria-estar-vinculada-baile-segun-sus-ultimas-pistas_96.jpg?crop=8036,4520,x0,y530&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T23:14:12+00:00'},
  {'author': 'Eire García Arbaizar | Roberto Fernández Ferreira',
   'title': 'Javier Calvo se suma a la teoría de Ambrossi: Mosca es Abraham Mateo',
   'description': 'La última actuación ha provocado que los Javis no dudasen en que es un artista de profesión.\xa0',
   'url': 'https://www.antena3.com/programas/mask-singer/javier-calvo-suma-teoria-ambrossi-mosca-abraham-mateo_20241212675a1b819439f90001e09710.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/11/64F37FF8-5853-4EF1-B5C1-E9580C4C4799/javier-calvo-suma-teoria-ambrossi-mosca-abraham-mateo_96.jpg?crop=1183,665,x0,y72&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T23:08:49+00:00'},
  {'author': 'Roberto Fernández Ferreira',
   'title': 'Mosca lo da todo en la Gran Final con ‘Stayin’ Alive’ de Bee Gees',
   'description': 'El insecto más marchoso de la temporada ha puesto toda la carne en el asador con una actuación espectacular.\xa0',
   'url': 'https://www.antena3.com/programas/mask-singer/mosca-todo-gran-final-stayin-alive-bee-gees_20241212675a19eaa42582000137ae46.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/11/C9AC5A67-97E4-4E2B-AC88-2EAFE5EFBC5A/mosca-todo-gran-final-stayin-alive-bee-gees_96.jpg?crop=1191,670,x0,y27&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T23:02:02+00:00'},
  {'author': 'Roberto Fernández Ferreira',
   'title': '“A veces puedo parecer un poco repelente”: las pistas de Mosca en la Final de Mask Singer',
   'description': 'La finalista ha desvelado sus últimas pistas. ¿Habrá resuelto todas las dudas de los investigadores?\xa0',
   'url': 'https://www.antena3.com/programas/mask-singer/veces-puedo-parecer-poco-repelente-pistas-mosca-final_20241211675a1963a42582000137adc3.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/11/9AE3EEF6-3FA0-489E-99FD-EEE9B410A448/veces-puedo-parecer-poco-repelente-pistas-mosca-final-mask-singer_96.jpg?crop=1187,668,x0,y37&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T22:59:47+00:00'},
  {'author': 'Juan, Pizarro',
   'title': 'La Asamblea General de la ONU pide un alto el fuego en Gaza con nueve votos en contra, entre ellos Israel, EEUU, Hungría y Argentina',
   'description': '¿Por qué es importante?: La mayor parte de los países del mundo muestran de esta forma su rechazo a la masacre israelí contra la población civil palestina. Tan solo los países gobernados por la extrema derecha han votado en contra.',
   'url': 'https://www.lasexta.com/noticias/internacional/asamblea-general-onu-pide-alto-fuego-gaza-nueve-votos-ellos-israel-eeuu-hungria-argentina_20241211675a172aa42582000137ac51.html',
   'source': 'lasextanoticias',
   'image': 'https://fotografias.lasexta.com/clipping/cmsimages01/2024/12/11/2DCE3A15-8AB8-4F4F-B1E6-6905E0FBA3AB/asamblea-general-onu_96.jpg?crop=5760,3240,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T22:50:18+00:00'},
  {'author': 'Eire García Arbaizar',
   'title': '“No soy Joaquín Sánchez": las teorías de los investigadores se rompen en pedazos',
   'description': 'La pista extra ha descuadrado a todos y se han lanzado al vacío con nuevas propuestas.\xa0\xa0',
   'url': 'https://www.antena3.com/programas/mask-singer/soy-joaquin-sanchez-teorias-investigadores-rompen-pedazos_20241211675a154da42582000137ab48.html',
   'source': 'antena3',
   'image': 'https://fotografias.antena3.com/clipping/cmsimages01/2024/12/11/B0DF164E-20C5-4045-A634-CE0183A349EC/soy-joaquin-sanchez-teorias-investigadores-rompen-pedazos_96.jpg?crop=8256,4644,x0,y0&width=1200&height=675&optimize=low&format=webply',
   'category': 'general',
   'language': 'es',
   'country': 'es',
   'published_at': '2024-12-11T22:42:21+00:00'},
  {'author': 'lasextacom',

In [23]:
for noticia in json.loads(response.content)['data']:
    print(noticia['author'], noticia['title'])

efe Robert Kennedy Jr. propone a su nuera como subdirectora de la CIA para esclarecer el asesinato de JFK
europa-press El Ejército israelí inicia su retirada del sur de Líbano
lasextacom | agencias Cataluña activa la prealerta por posibles riadas en cuatro comarcas de Tarragona debido a lluvias intensas
efe Trump planea permitir arrestos de inmigrantes en escuelas, iglesias y juzgados
lasexta-deportes Jorge Martín carga contra Ducati: "El trato que tuvieron no me gustó"
Gema, Soubrier Basi y su familia, arruinados por su 'inquiokupa', un refugiado sirio: "Yo también soy vulnerable"
Alberto Mendo Así engañó Abraham Mateo a su ídolo, David Bustamante, para que no le reconociera en Mask Singer
lasextacom Última hora política, en directo | Ábalos declara en el Supremo para intentar "desmontar" las acusaciones de Aldama y la UCO
lasexta-deportes Ducati señala qué es lo que más les ha impresionado de Marc Márquez
efe Consumo investiga a empresas que gestionan cientos de pisos turísticos por posibles "prácticas engañosas"
alfonso-perez-medina La Fiscalía intentará demostrar durante el interrogatorio que Ábalos era el "superjefe" de una organización criminal
Roberto Fernández Ferreira Abraham Mateo se destapa como Mosca y gana la cuarta temporada de Mask Singer
Roberto Fernández Ferreira ¡Adriana Ugarte era Cobra!: la actriz ha sido desenmascarada en la Gran Final de Mask Singer
Eire García Arbaizar ¡Cobra VS Mosca! Así ha sido el asalto final en Mask Singer
Roberto Fernández Ferreira Manuel Díaz, 'El Cordobés', cambia el toro por el Tiburón en Mask Singer: ¡Así ha sido su desenmascaramiento!
Eire García Arbaizar ¡Tiburón VS Cobra! Así ha sido el primer asalto de la Gran Final
Patri Bea ¡Hipnótica! Cobra brilla con Las 12 en la gran final de Mask Singer
Patri Bea “Mi buen reptar me ha dado más de una alegría”: Cobra podría estar vinculada con el baile según sus últimas pistas
Eire García Arbaizar | Roberto Fernández Ferreira Javier Calvo se suma a la teoría de Ambrossi: Mosca es Abraham Mateo
Roberto Fernández Ferreira Mosca lo da todo en la Gran Final con ‘Stayin’ Alive’ de Bee Gees
Roberto Fernández Ferreira “A veces puedo parecer un poco repelente”: las pistas de Mosca en la Final de Mask Singer
Juan, Pizarro La Asamblea General de la ONU pide un alto el fuego en Gaza con nueve votos en contra, entre ellos Israel, EEUU, Hungría y Argentina
Eire García Arbaizar “No soy Joaquín Sánchez": las teorías de los investigadores se rompen en pedazos
lasextacom Feijóo el abismo económico: todas las veces que el líder del PP criticó la economía española
lasextacom Las relaciones de España con la familia Assad: cordialidad hasta el estallido de la Primavera Árabe
Eire García Arbaizar ¡Directo al estrellato! Tiburón hace temblar el escenario con ‘Enamorado de la moda juvenil’
Eire García Arbaizar La tercera ley de Newton y el puesto número 3: estas son las nuevas pistas de Tiburón
Eire García Arbaizar ¡Menudo show! Javier Ambrossi marca el inicio de la Gran Final de Mask Singer
Alex, Voytyuk Los rebeldes destapan el negocio de Al Assad con el captagon, la "cocaína de los pobres"
Sara, Rincón Comienza el juicio en Valladolid por el asesinato de Paloma e India: su agresor se enfrenta a prisión permanente revisable
julian-garcia Ferran Torres sólo necesita quince minutos
lasextacom | agencias Declarados culpables el padre y la madrastra de Sara Sharif, la niña de 10 años que fue sometida a un trato atroz y brutal
Roberto Fernández Ferreira | Patri Bea Alaska se sincera sobre sus operaciones estéticas: "Para mí es crearte y construirte"
Juan, V. Rivero | thais-munoz La revolución económica de los PIGS: España, Portugal, Italia y Grecia salen al rescate del antiguo motor europeo
esther-redondo El PP tacha de "inventada" las graves acusaciones de Sánchez y las asociaciones niegan un "frente judicial contra el Gobierno"
Alberto Mendo ¿Caerán en la tentación? El dilema de Manu y Rosa en El Rosco: “Es más probable que la líe”
lasextacom | europa-press Las aplicaciones Whatsapp, Instagram y Facebook sufren una caída a nivel mundial
Alberto Mendo Rosa, al borde de las lágrimas al dedicar El Rosco a sus padres: “Yo no nací aquí”
Alberto Mendo La reflexión de Wally López en Pasapalabra: “El talento debe ser premiado”
Alberto Mendo Ana Jara debuta en Pasapalabra con victoria en La Pista: “En casa se ve más fácil”
Juan, Pizarro Felipe VI ataca las dictaduras de Franco y Musolini en su discurso desde Italia: "El pasado no ha de repetirse ni como caricatura"
Sara Sanz "Solo espero que me deje en paz": las lágrimas de Antonio Canales al hablar de su casera
Sara Sanz Antonio Canales aclara qué relación tiene con Bernardo 'El Asturiano': "No me he tatuado su nombre"
Sara Sanz Antonio Canales, indignado ante las acusaciones de su casera: "No debo ni un duro, la deuda es inexistente"
lasexta-deportes Fernando Alonso ya lo avisó: el ranking definitivo de la F1 coloca a Lando Norris por encima de Verstappen
lasextacom El Gobierno y sus socios llegan a un acuerdo para prorrogar el impuesto energético en ausencia del PNV y Junts
Sara Sanz Eva quiere encontrar al padre que renegó de ella: "Ya no sé si está vivo o muerto"
Sara Sanz Los padres de la víctima que ha declarado contra la banda de agresores de Vigo: "No les bastó con la paliza"
lasexta-deportes Las sedes de España para el Mundial 2030
Sara Sanz Hablamos con una cuidadora de personas mayores acusada de robar a varias familias: "Nos quitó 30.000 euros"
Cristina García Chacón ¿Una ensalada diferente y original? Descubre las ensaladas más top de Arguiñano para comenzar un menú festivo
Sara Sanz La broma de un joven a sus padres por la que casi le echan de casa: "Dejó de ser broma cuando la vi llorar"
lasextacom La justicia gallega rechaza incrementar el permiso de paternindad de 16 semanas para igualarlo a las 22 del de maternidad
Gonzalo, Barbero '¿Es el enemigo?', una película homenaje a Miguel Gila: el cómico que hizo reír a España en tiempos de guerra
Sara Sanz Nieves, a punto de ser desahuciada por su suegra y sus cuñadas: "Nos van a echar a la calle"
lasexta-deportes El mensaje de ilusión de De la Rosa: "Lo que viene a Aston Martin es el motivo por el que yo fiché..."
pedro-gomez La Audiencia Nacional condena a 74 años de cárcel a cuatro etarras por intentar asesinar a dos periodistas
lasextacom Mazón sigue adelante con su Plan Simplifica que permite construir en zonas inundables
Sara Sanz El fenómeno de Luigi Magnione, acusado de matar al CEO de UnitedHealthcare: ¿un asesino convertido en héroe?
Sara Sanz Las medidas desconocidas que deben cumplirse durante los viajes de Estado de los reyes de España
lasextacom Los padres de uno de los menores agredidos en Vigo denuncian que su hijo "recibe amenazas de 200 teléfonos" y que los agresores siguen en libertad
Julia Zapata Avance del próximo capítulo de Sueños de libertad: Don Pedro y Digna, a punto de besarse...¿podrán controlarse?
Julia Zapata Capítulo 202 de Sueños de libertad; 11 de diciembre: Fina se niega a contarle a Marta lo que ocurrió con Santiago
lasextacom Luigi Mangione, el presunto asesino del CEO de United Healthcare se declara no culpable en un juzgado de Pensilvania (EEUU)
lasexta-deportes Oficial: el Mundial 2030 se disputará en España, Portugal y Marruecos
Julia Zapata María utiliza a Gema para que Begoña se entere de que Andrés y ella pararon la noche juntos
alfonso-perez-medina El plan de Ábalos ante el juez: contestará a todas las partes, incluido el PP, y negará las acusaciones
alfonso-perez-medina La jueza contesta a la Fiscalía que hay correos que pueden ser delictivos sobre el cargo del hermano de Sánchez
Vanesa, Sáez Fraile | pelayo-alvarez El precio de divulgar ciencia: amenazas, insultos y acoso, un problema que afecta especialmente a las mujeres
Julia Zapata “Me cobraré el favor”: Jesús considera que Marta se ha aprovechado de él para sacar a Fina de la cárcel
lasexta-deportes Un piloto de Ducati intenta 'reclutar' a Pedro Acosta: "Me gustaría..."
Julia Zapata Andrés rechaza a María tras acostarse con ella: “Tenemos que hacer como si no hubiese ocurrido”
Carlos, Martín Oposiciones para el Cuerpo de Arsenales de la Armada: requisitos, fechas y exámenes
lasextacom | servimedia Ayuso acepta las condiciones del Gobierno para la creación de 1.091 nuevas plazas de profesores universitarios
Julia Zapata Joaquín no se arrepiente de su beso con Miriam y se sincera con ella: “No dejo de pensar en ti”
lasextacom Guerra Ucrania - Rusia | Putin descarta la utilización de armas nucleares en Ucrania
Sohaib, Nadi Los sirios buscan a sus familias en las morgues del hospital de Damasco: "Ahora todos los cadáveres están quemados"
Andrés, Pantoja ¿Se benefician conscientemente los famosos de su popularidad?: "No he aprovechado la fama para ligar, otra cosa es..."
lasexta-deportes Fernando Alonso elige al gran campeón del futuro en la Fórmula 1
lasextacom De California a Manresa para rescatar a su hermana de una secta: "El cura me agarró y me tiró al suelo"
lasexta-deportes La desesperación que Ducati vivió con Valentino Rossi: "Hicimos siete versiones de motos diferentes"
borja-g-collado Asma Al Assad, una "rosa en el desierto" para blanquear el sangriento régimen sirio
lasexta-deportes Fernando Alonso pone fecha a su retirada... con matices
esther-redondo Sánchez insinúa que el PP actúa en connivencia con algún juez: "Juegan con las cartas marcadas"
Laura, Simón La desesperación de Rita con su hijo autista: "Nos muerde, se autolesiona... mi hijo está sufriendo"
Andrés, Pantoja La elaborada estafa a una mujer que pierde sus ahorros por un anuncio: "Al principio no me fío"
Ana, Estévez Sánchez Miriam González, mujer del exviceprimer ministro del Reino Unido: "No hay excusa para no asistir a Notre Dame"
esther-redondo Sánchez asegura que presentarán los Presupuestos "sí o sí" y responde a Junts: "Voy a sudar la camiseta y más"
Laura, Simón Vecinos de Murcia, contra los gorrillas: "Defecan y se masturban en la calle y acosan a las chicas"
lasextacom Siria retoma la normalidad con un Al Golani centrado en dar una imagen de moderación: "No habrá otra guerra"
Cristina García Chacón Un postre de Eva Arguiñano, perfecto para esta Navidad: milhojas de chocolate y nata
lasexta-deportes Hamilton señala quién es el "mejor campeón del mundo" contra el que ha competido en F1
lasextacom | agencias Tertsch y Buxadé (Vox) intentan boicotear una charla de Zapatero sobre violencia machista en la Eurocámara
lasextacom | maria-llapart Ábalos dice que nunca se "tenía que haber fiado" de Koldo y carga contra Aldama: "No tiene ninguna prueba, solo quiere la libertad"
lasextacom | agencias Israel aprovecha la caída de Al Assad para ocupar territorio sirio y destruye el 70% de sus capacidades militares
Andrés, Pantoja "¡Por Dios, qué error más grande!": Carmen Duerto valora las palabras de la reina Letizia en el funeral de la DANA
lasextacom Vivienda e inmigración a escala europea, lo que más preocupa a los españoles, según el Eurobarómetro
ruth-rincon Investigan por qué no avisó la pulsera telemática del asesino machista de Mallorca
lasexta-deportes Fernando Alonso pide a Aston Martin que emule a McLaren
Raúl, García García Drogarse en el trabajo: "Contaba mi nómina en gramos de cocaína"

In [ ]:
url = "http://api.mediastack.com/v1/news?access_key=67f7b286232bf5d45c0e7aeb1848c0fb"

params = {'sources': 'antena3, lasextanoticias',
          'countries': 'es',
          'languages': 'es',
          'date': '2024-12-12',
          'limit': 100,
          'offset': 0}

response = requests.get(url, params=params)

my_news = {
            "autor": [],
            "titulo": [],
            "descripcion": [],
            "url": [],
            "fuente": [],
            "fecha_publicacion": []
            }

for noticia in json.loads(response.content)['data']:
    my_news['autor'].append(noticia['author'])
    my_news['titulo'].append(noticia['title'])
    my_news['descripcion'].append(noticia['description'])
    my_news['url'].append(noticia['url'])
    my_news['fuente'].append(noticia['source'])
    my_news['fecha_publicacion'].append(noticia['published_at'])

pd.DataFrame(my_news)

,autor,titulo,descripcion,url,fuente,fecha_publicacion
0,Carmen Pardo,Telmo revela la amenaza de Rodrigo a Lucía: “N...,El joven le cuenta a Lucía la amenaza que reci...,https://www.antena3.com/series/beguinas/telmo-...,antena3,2024-12-12T23:31:39+00:00
1,lasextacom,Los coches sin distintivo medioambiental empad...,El Ayuntamiento de Madrid rectifica su nueva n...,https://www.lasexta.com/noticias/sociedad/coch...,lasextanoticias,2024-12-12T22:14:51+00:00
2,"María, Sanz",Las evidencias que señalan a Luigi Mangione co...,¿Cuáles son?: La Policía de Nueva York ha expl...,https://www.lasexta.com/noticias/internacional...,lasextanoticias,2024-12-12T22:14:24+00:00
3,lasextacom,Un equipo de la CNN encuentra a un prisionero ...,Como se puede ver en el vídeo que acompaña est...,https://www.lasexta.com/noticias/internacional...,lasextanoticias,2024-12-12T21:39:26+00:00
4,lasextacom,La Guardia Civil pide colaboración ciudadana p...,El contexto: La madrugada de este jueves emple...,https://www.lasexta.com/noticias/sociedad/guar...,lasextanoticias,2024-12-12T21:36:37+00:00
...,...,...,...,...,...,...
95,"Laura, Simón","Cuca Gamarra: ""En 2021 Pedro Sánchez tapó la c...","Cuca Gamarra cree que Pedro Sánchez ""debería d...",https://www.antena3.com/programas/espejo-publi...,antena3,2024-12-12T10:11:50+00:00
96,lasextacom,Las Fuerzas Armadas encuentran un cadáver en P...,El hallazgo ha tenido lugar en la mañana de es...,https://www.lasexta.com/noticias/sociedad/fuer...,lasextanoticias,2024-12-12T10:09:34+00:00
97,lasextacom | efe,"El presidente surcoreano Yoon, desafiante: def...",Un futuro incierto: Yoon ha pronunciado un dis...,https://www.lasexta.com/noticias/internacional...,lasextanoticias,2024-12-12T09:47:55+00:00
98,lasexta-deportes,Ferrari se encomienda a Hamilton para vencer a...,"Fred Vasseur, jefe de la escudería italiana, h...",https://www.lasexta.com/noticias/deportes/moto...,lasextanoticias,2024-12-12T09:31:43+00:00
99,alfonso-perez-medina,La fiscalía sueca archiva la investigación por...,La fiscalía sueca ha decidido cerrar la invest...,https://www.lasexta.com/noticias/deportes/futb...,lasextanoticias,2024-12-12T09:14:48+00:00

In [29]:
def json_to_dict(json, news_dict):
    for noticia in json:
        news_dict['autor'].append(noticia['author'])
        news_dict['titulo'].append(noticia['title'])
        news_dict['descripcion'].append(noticia['description'])
        news_dict['url'].append(noticia['url'])
        news_dict['fuente'].append(noticia['source'])
        news_dict['fecha_publicacion'].append(noticia['published_at'])
    return news_dict

In [36]:
url = "http://api.mediastack.com/v1/news?access_key=67f7b286232bf5d45c0e7aeb1848c0fb"

params = {'sources': 'antena3, lasextanoticias',
          'countries': 'es',
          'languages': 'es',
          'date': '2024-12-12',
          'limit': 100,
          'offset': 0}

my_news = {
            "autor": [],
            "titulo": [],
            "descripcion": [],
            "url": [],
            "fuente": [],
            "fecha_publicacion": []
            }

while len(my_news['autor']) < json.loads(response.content)['pagination']['total']:
    print("Nueva llamada")
    response = requests.get(url, params=params)
    my_news = json_to_dict(json.loads(response.content)['data'], my_news)
    params['offset'] = params['offset'] + 100


df_news = pd.DataFrame(my_news)
df_news.to_csv('./data/news_' + params['date'] + '.csv')

Nueva llamada
Nueva llamada
Nueva llamada
Nueva llamada
Nueva llamada
Nueva llamada
Nueva llamada
Nueva llamada
Nueva llamada
Nueva llamada

In [37]:
df_news

,autor,titulo,descripcion,url,fuente,fecha_publicacion
0,Carmen Pardo,"Telmo revela la amenaza de Rodrigo a Lucía: “No temo por mi vida, sino por la vuestra”",El joven le cuenta a Lucía la amenaza que recibió por parte de su prometido si no abandonaba Segovia cuando saliera de la cárcel.,https://www.antena3.com/series/beguinas/telmo-revela-amenaza-rodrigo-lucia-temo-vida-sino-vuestra_20241213675b725b2c0dde00012d2afa.html,antena3,2024-12-12T23:31:39+00:00
1,lasextacom,Los coches sin distintivo medioambiental empadronados en Madrid podrán seguir circulando hasta 2026,El Ayuntamiento de Madrid rectifica su nueva normativa contra los vehículos contaminantes y anuncia tres excepciones que les permitirá circular por las calles de la capital hasta 2026.,https://www.lasexta.com/noticias/sociedad/coches-distintivo-medioambiental-empadronados-madrid-podran-seguir-circulando-2026_20241212675b605b2c0dde00012d1f2e.html,lasextanoticias,2024-12-12T22:14:51+00:00
2,"María, Sanz",Las evidencias que señalan a Luigi Mangione como presunto asesino del CEO de United Healthcare,¿Cuáles son?: La Policía de Nueva York ha explicado que las balas encontradas en la escena del crimen concuerdan con el arma que se le encontró durante la detención. También casan las huellas encontradas en una botella.,https://www.lasexta.com/noticias/internacional/evidencias-que-senalan-luigi-mangione-como-presunto-asesino-ceo-united-healthcare_20241212675b60412c0dde00012d1f03.html,lasextanoticias,2024-12-12T22:14:24+00:00
3,lasextacom,Un equipo de la CNN encuentra a un prisionero que llevaba tres meses sin ver la luz en una de las cárceles de Al Assad,"Como se puede ver en el vídeo que acompaña esta noticia, el hombre está sediento, asustado y aturdido. No sabe lo que está pasando. Cuando le comunican que ""Siria es libre"" tras la caída del régimen de Al Assad, rompe a llorar.",https://www.lasexta.com/noticias/internacional/equipo-cnn-encuentra-prisionero-que-llevaba-tres-meses-ver-luz-carceles-assad_20241212675b580e6495a1000156d53d.html,lasextanoticias,2024-12-12T21:39:26+00:00
4,lasextacom,La Guardia Civil pide colaboración ciudadana para averiguar quién ha dejado el cadáver de un bebé en Loeches (Madrid),El contexto: La madrugada de este jueves empleados de la planta de reciclaje de Loeches encontraban los restos mortales de un neonato de unas dos semanas de vida. Según el primer exámen forense el bebé podría presentar signos de asfixia.,https://www.lasexta.com/noticias/sociedad/guardia-civil-pide-colaboracion-ciudadana-averiguar-quien-dejado-cadaver-bebe-loeches-madrid_20241212675b57656495a1000156d4b8.html,lasextanoticias,2024-12-12T21:36:37+00:00
...,...,...,...,...,...,...
991,lasextacom,"Ayuso denuncia una ""operación de Estado"" contra ella por el fraude de su pareja: ""Querían mandar gotitas de cianuro""","A ojos de la presidenta madrileña ""todos los poderes del Estado""se han organizado para derribarla mediante la filtración de los correos en los que la defensa de su novio admitía que el empresario había defraudado a Hacienda.",https://www.lasexta.com/noticias/nacional/ayuso-denuncia-operacion-estado-ella-fraude-pareja-querian-mandar-gotitas-cianuro_20241201674c48bb1258380001f0976a.html,lasextanoticias,2024-12-01T11:30:03+00:00
992,Roberto Fernández Ferreira,¿Por qué se come pavo el Día de Acción de Gracias? Tamara Falcó explica la tradición estadounidense,La colaboradora ha desvelado cómo es la mítica receta americana y ha contado por qué es tan tradicional ese plato.,https://www.antena3.com/programas/el-hormiguero/que-come-pavo-dia-accion-gracias-tamara-falco-explica-tradicion-estadounidense_20241201674c477b85d24c0001cc245f.html,antena3,2024-12-01T11:24:43+00:00
993,Alberto Mendo,Ataque de risa en pleno directo: Pablo López confiesa cómo fue su primer beso... ¡con Laura Pausini!,Pablo López y Antonio Orozco se han enfrentado a una ruleta llena de preguntas incómodas y han dejado respuestas sorprendentes.,https://www.antena3.com/programas/la-voz/ataque-risa-pleno-directo-pablo-lopez-confiesa-primer-beso-laura-pausini_20241201674c46077337f20001b17915.html,antena3,2024-12-01T11:18:31+00:00
994,lasexta-deportes,La polémica sanción que deja a Verstappen sin 'pole' en el Gran Premio de Catar,El neerlandés firmó el mejor tiempo de toda la clasificación pero un lance en la sesión con George Russell terminó con la FIA sancionando a Max con una posición en la parrilla de salida.,https://www.lasexta.com/noticias/deportes/motor/formula1/sancion-que-deja-verstappen-pole-gran-premio-catar_20241201674c43a67337f20001b17785.html,lasextanoticias,2024-12-01T11:08:22+00:00
995,lasextacom | agencias,Al menos ocho muertos en Alepo por ataques rusos que no frenan a los rebeldes sirios,[[IntroductionHighlight:¿Por qué es importante?]] Las nuevas víctimas mortales se suman a las 350 registradas en los últimos cuatro días de ofensiva insurgente.,https://www.lasexta.com/noticias/internacional/menos-ocho-muertos-alepo-ataques-rusos-que-frenan-rebeldes-sirios_20241201674c324585d24c0001cc15c8.html,lasextanoticias,2024-12-01T09:54:13+00:00

In [41]:
from dotenv import dotenv_values

config = dotenv_values(".env")

In [44]:
config['access_key']

'67f7b286232bf5d45c0e7aeb1848c0fb'